Improve language in README.md
qarmin/szyszka pull request #16
Opened 2021-05-14 22:50 UTC by azadad96

Edited some of the README.md to fix typos or reformulate the sentences.
It's not perfect yet, since I wasn't always completely sure what was meant by the original author.

2021-05-14 23:28 UTC, biru-cs requested changes
You fixed a lot of typos and grammar errors, but I also improved a couple of lines. Nice job :)

2021-05-14 23:28 UTC, biru-cs commented on README.md
> +Packed zip file contains all dependencies, but if you want to, you can install https://github.com/tschoonj/GTK-for-Windows-Runtime-Environment-Installer/releases and move file whatever you want.
...if you want to, you can install **the GTK runtime from** (link)...

2021-05-14 23:28 UTC, biru-cs commented on README.md
> +- Allow adding folders
Allow folder addition

2021-05-16 19:14 UTC, qarmin commented
Needs rebase after recent changes

2021-05-20 13:45 UTC, merged

2021-05-20 13:45 UTC, qarmin commented
Thanks!